config/routes.rb
JainManish::Application.routes.draw do
  resources :request_forms

  devise_for :users

  root 'welcome#index'

  get '/about' => 'welcome#about', :as=> 'about'
  get '/my-skill' => 'welcome#skill', :as=> 'skill'
  get '/portfolio' => 'welcome#portfolio', :as=> 'portfolio'
  get '/resume' => 'welcome#resume', :as=> 'resume'
  get '/contact-me' => 'welcome#contact', :as=> 'contact'

  resources :posts do
    resources :comments
  end
  

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
	has_many :comments, dependent: :destroy
	validates :title, presence: true,
                    length: { minimum: 5 }
end

app/models/request_form.rb
class RequestForm < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

 private
  def authenticate_user
    unless current_user.try(:is_admin) == true
      flash[:error] = "Access Denied"
      redirect_to root_path
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	# http_basic_authenticate_with name: "manish", password: "secret", only: :destroy
	 before_action :authenticate_user, only: [:destroy]

	def create
	@post = Post.find(params[:post_id])
    @comment = @post.comments.create(params[:comment].permit(:commenter, :body))
    redirect_to post_path(@post)
	end

	def destroy
	  @post = Post.find(params[:post_id])
	  @comment = @post.comments.find(params[:id])
	  @comment.destroy
	  redirect_to post_path(@post)
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

	# http_basic_authenticate_with name: "manish", password: "secret", except: [:index, :show]
  before_action :authenticate_user, except: [:index, :show]

	def new
		@post = Post.new
	end

	def create
 		@post = Post.new(post_params)

  	if @post.save
  		redirect_to @post
  	else
  		render 'new'
  	end
  end

  def show
  	@post = Post.find(params[:id])
	end

	def index
    @posts = Post.all
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
 
	  if @post.update(params[:post].permit(:title, :text))
	    redirect_to @post
	  else
	    render 'edit'
	  end
	end

	def destroy
  	@post = Post.find(params[:id])
  	@post.destroy
 
  	redirect_to posts_path
	end


  private
  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/controllers/request_forms_controller.rb
class RequestFormsController < ApplicationController
  before_action :set_request_form, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user, except: [:new, :create]

  # GET /request_forms
  # GET /request_forms.json
  def index
    @request_forms = RequestForm.all
  end

  # GET /request_forms/1
  # GET /request_forms/1.json
  def show
  end

  # GET /request_forms/new
  def new
    @request_form = RequestForm.new
  end

  # GET /request_forms/1/edit
  def edit
  end

  # POST /request_forms
  # POST /request_forms.json
  def create
    @request_form = RequestForm.new(request_form_params)

    respond_to do |format|
      if @request_form.save
        format.html { redirect_to new_request_form_path, notice: 'thank you ! Request form was successfully saved. will reply as soon as possible.' }
        format.json { render action: 'show', status: :created, location: @request_form }
      else
        format.html { render action: 'new' }
        format.json { render json: @request_form.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /request_forms/1
  # PATCH/PUT /request_forms/1.json
  def update
    respond_to do |format|
      if @request_form.update(request_form_params)
        format.html { redirect_to @request_form, notice: 'Request form was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @request_form.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /request_forms/1
  # DELETE /request_forms/1.json
  def destroy
    @request_form.destroy
    respond_to do |format|
      format.html { redirect_to request_forms_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_request_form
      @request_form = RequestForm.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def request_form_params
      params.require(:request_form).permit(:name, :email, :message)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def index
	end

	def about
	end

	def skill
	end

	def portfolio
	end

	def resume
	end

	def contact
	end

	def create_contact
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/request_forms_helper.rb
module RequestFormsHelper
end

app/views/comments/_comment.html.erb
<p>
  <strong>Commenter:</strong>
  <%= comment.commenter %>
</p>
 
<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>

<p>
  <%= link_to 'Destroy Comment', [comment.post, comment],
               method: :delete,
               data: { confirm: 'Are you sure?' } if current_user.try(:is_admin) == true %>
</p>

app/views/comments/_form.html.erb
<%= form_for([@post, @post.comments.build]) do |f| %>
  <p>
    <%= f.label :commenter %><br />
    <%= f.text_field :commenter %>
  </p>
  <p>
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <div class="container footer-text">
    <center>
      <p>
        <%= link_to 'My skill', skill_path %> &nbsp &nbsp | &nbsp &nbsp
        <%= link_to 'Blog', posts_path %> &nbsp &nbsp | &nbsp &nbsp
        <%= link_to 'Portfolio', portfolio_path %> &nbsp &nbsp | &nbsp &nbsp
        <%= link_to 'Resume', resume_path %> &nbsp &nbsp | &nbsp &nbsp
        <%= link_to 'Contact Me', '#' %>&nbsp &nbsp | &nbsp &nbsp
        <% if user_signed_in? %>
          Welcome <%= current_user.email %>
          <%= link_to 'logout', destroy_user_session_path, :method => :delete %>
        <% else %>
          <%= link_to 'Login', new_user_session_path %>
        <% end %>
      </p>
    </center>
<!--     <div class="row">
      <div class="span2">
        <h4><i class="icon-star icon-white"></i> Projects</h4>
        <nav>
          <ul class="quick-links">
            <li><a href="product.html">Project1</a></li>
            <li><a href="product.html">Project2</a></li>
            <li><a href="product.html">Project3</a></li>
            <li><a href="all_products.html">All projects</a></li>
          </ul>
        </nav>
      </div>
      <div class="span2">
        <h4><i class="icon-beaker icon-white"></i> About</h4>
        <nav>
          <ul class="quick-links">
            <li><%= link_to 'My skill', skill_path %></li>
            <li><%= link_to 'Blog', posts_path %></li>
            <li><%= link_to 'Portfolio', portfolio_path %></li>
            <li><%= link_to 'Resume', resume_path %></li>
            <li><%= link_to 'Events', '#' %></li>
          <ul>
        </ul></ul></nav>          
      </div>
      <div class="span2">
        <h4><i class="icon-thumbs-up icon-white"></i> Support</h4>
        <nav>
          <ul class="quick-links">
            <li><a href="#">FAQ</a></li>
            <li><%= link_to 'Contact', contact_path %></li>
          </ul>
        </nav>
      </div>
      <div class="span3">
        <h4><i class="icon-hand-right icon-white"></i> Get in touch</h4>
        <div class="social-icons-row">
          <a href="#"><i class="icon-twitter"></i></a>
          <a href="#"><i class="icon-facebook"></i></a>
          <a href="#"><i class="icon-linkedin"></i></a>                                         
        </div>
        <div class="social-icons-row">
          <a href="#"><i class="icon-google-plus"></i></a>              
          <a href="#"><i class="icon-github"></i></a>
          <a href="mailto:manijain333@gmail.com"><i class="icon-envelope"></i></a>        
        </div>
      </div>
    </div>
  -->
  <hr class="footer-divider">
    <a class="visitor_total" href="javascript:void(0);"> Total Visitors </a>
    <a href="http://guestscounter.com"><img src="http://guestscounter.com/count.php?c_style=2&id=1392230634" border=0 alt="free counter"></a><br><a href="http://guestscounter.com" style="font-size:9px;"></a>&nbsp

    <p class= "pull-right">
      <small>Develop & Design By &nbsp <a href="/">Manish Jain</a> &nbsp <i class="icon-beaker"></i></small>
    </p>
     </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <!-- Start: Navigation wrapper -->
  <div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container devroye", id="home_page_contents">
        <%= link_to "MANISH JAIN", root_path, class: 'brand brand-bootbus' %>
        <!-- <a class="brand brand-bootbus" href="index.html">MANISH JAIN</a> -->
        <!-- Below button used for responsive navigation -->
        <button data-target=".nav-collapse" data-toggle="collapse" class="btn btn-navbar" type="button">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <!-- Start: Primary navigation -->
        <div class="nav-collapse collapse">        
          <ul class="nav pull-right">
            <li><%= link_to "ABOUT ME", about_path %></li>
            <li><%= link_to "MY SKILL", skill_path %></li>
            <li><%= link_to "PORTFOLIO", portfolio_path %></li>
            <li><%= link_to "RESUME", resume_path %></li>
            <li><%= link_to "BLOG", posts_path %></li>
            <li><%= link_to "CONTACT ME", new_request_form_path %></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
      <!-- End: Navigation wrapper -->
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>JainManish</title>
  <link href="http://localhost:3000/assets/icon-title.ico" rel="shortcut icon" />
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

	<%= render :partial => "/layouts/header" %>
	<% if notice %>
  		<p class="alert alert-success"><%= notice %></p>
	<% end %>
	<% if alert %>
  		<p class="alert alert-danger"><%= alert %></p>
	<% end %>
	
	<%= yield %>
	<%= render :partial => "/layouts/footer" %>

	<script src="assets/jquery.min.js" type="text/javascript"></script>
	<script src="assets/bootstrap.min.js" type="text/javascript"></script>
	<script src="assets/boot-business.js" type="text/javascript"></script>
	<script src="assets/bootstrap.js" type="text/javascript"></script>
</body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
  <% if @post.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@post.errors.count, "error") %> prohibited
      this post from being saved:</h2>
    <ul>
    <% @post.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/posts/edit.html.erb
<h1>Edit post</h1>

<%= render 'form' %>
 
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<div class="content devroye", id="home_page_contents">
  <!-- Start: slider -->
  <div class="item">
    <div class="hero-unit">
      <div class="page-header">
        <h2><i class="icon-briefcase"></i> My Blog</h2>
      </div>
      <h1>Listing posts</h1>
      <%= link_to 'New post', new_post_path if current_user.try(:is_admin) == true %>
 
      <table class= "table table-condensed">
        <tr>
          <th width="30%">Title</th>
          <th width="30%">Text</th>
          <th></th>
        </tr>
       
        <% @posts.each do |post| %>
          <tr>
            <td width="30%"><%= post.title %></td>
            <td width="30%"><%= post.text %></td>
            <td><%= link_to 'Show', post %> |
            <% if current_user.try(:is_admin) == true %>
             <%= link_to 'Edit', edit_post_path(post) %> | <%= link_to 'Destroy', post_path(post), method: :delete, data: { confirm: 'Are you sure?' }  %>
            <% end %>
            </td>
          </tr>
        <% end %>
      </table>
    </div>
  </div>
</div>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p>
  <h3><%= @post.title %></h3>
</p><br>

<p>
  <h5><%= @post.text %></h5>
</p>
<br>

<h2>Comments</h2>
<%= render @post.comments %>
 
<h2>Add a comment:</h2>
<%= render "comments/form" %>
 
<%= link_to 'Edit Post', edit_post_path(@post) if current_user.try(:is_admin) == true %>
| <%= link_to 'Back to Posts', posts_path %>

app/views/request_forms/_form.html.erb
<%= form_for(@request_form) do |f| %>
  <% if @request_form.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@request_form.errors.count, "error") %> prohibited this request_form from being saved:</h2>

      <ul>
      <% @request_form.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="control-group">
    <div class="controls">
      <%= f.text_field :name, :placeholder => 'Name', :id => 'inputName' %>
    </div>
  </div>

  <div class="control-group">
    <div class="controls">
      <%= f.email_field :email, :placeholder => 'Email', :id => 'inputName' %>
    </div>
  </div>

  <div class="control-group">
    <div class="controls">
      <%= f.text_area :message, :placeholder => 'Message', :id => 'inputName' %>
    </div>
  </div>

  <div class="control-group">
    <div class="controls">
      <%= f.submit 'Submit', :class => 'btn btn-primary btn-large' %>
    </div>
  </div>

<% end %>

app/views/request_forms/edit.html.erb
<h1>Editing request_form</h1>

<%= render 'form' %>

<%= link_to 'Show', @request_form %> |
<%= link_to 'Back', request_forms_path %>

app/views/request_forms/index.html.erb
<h1>Listing request_forms</h1>

  <table class="table table-striped">
    <thead>
      <tr>
        <th width="20%">Name</th>
        <th width="20%">Email</th>
        <th width="30%">Message</th>
        <th width="30%"></th>
      </tr>
    </thead>

    <tbody>
      <% @request_forms.each do |request_form| %>
        <tr>
          <td><%= request_form.name %></td>
          <td><%= request_form.email %></td>
          <td><%= request_form.message %></td>
          <td><%= link_to 'Show', request_form %> | <%= link_to 'Edit', edit_request_form_path(request_form) %> | <%= link_to 'Destroy', request_form, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <br>

app/views/request_forms/new.html.erb
<div class="content devroye", id="home_page_contents">
  <div class="container">
    <div class="page-header">
      <h1><i class="icon-envelope-alt"></i> Contact us</h1>
      <% if current_user.try(:is_admin) == true %>
        <p class="pull-right">welcome, <%= current_user.try(:email) %></p><br>
        <%= link_to "show listing", request_forms_path %> | <%= link_to "Back", root_path %>
      <% end %>
    </div>
    <div class="row-fluid">
      <center>
        <h3>
          I’d love to hear from you. Interested in working together? Fill out the form below with some info about your project and I will get back to you as soon as I can. Please allow a couple days for me to respond.
        </h3>
      </center>
      <br>
      <!-- Start: CONTACT US FORM -->
      <div class="span4 offset1">
        <div class="page-header">
          <h3><i>Quick message</i></h3>
        </div>
        <%= render 'form' %>        
      </div>
      <!-- End: CONTACT US FORM -->
      <!-- Start: OFFICES -->
      <div class="span5 offset1">
        <div class="page-header">
          <h3><i>Get in touch with me</i></h3>
        </div>
        <!-- <h3></h3> -->
        <div>
          <address class="pull-left">
            <p><strong>phone :</strong><br>
            +91 - 9785394039</p>
            <p><strong>email :</strong><br>
            manijain333@gmail.com</p>
            <p><strong>Address :</strong><br>
            C58A, Bhartendu Chowk,<br>
            Ambabari, jaipur (Rajasthan)<br>
            302010<br>
          </address><br><br>
        </div>
      <!-- End: OFFICES -->
      </div>
    </div>
  </div>
</div>

app/views/request_forms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @request_form.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @request_form.email %>
</p>

<p>
  <strong>Message:</strong>
  <%= @request_form.message %>
</p>

<%= link_to 'Edit', edit_request_form_path(@request_form) %> |
<%= link_to 'Back', request_forms_path %>

app/views/welcome/about.html.erb
<div class="content devroye", id="home_page_contents">
  <!-- Start: slider -->
  <div class="item">
  <div class="hero-unit">
    <div class="page-header">
      <h2><i class="icon-user"></i> About Me</h2>
    </div>
    <h3>Approach</h3>
    <p>My work approach draws on my background in design, my love of Ruby on Rails, and the art of software craftsmanship.</p>

    <h3>Agile</h3>
    <p>I follow Agile principles, making customers happy through the early and continuous delivery of software. I anticipate and welcome changing requirements. I send email or chat with client every day and when working with a team, have daily stand-ups and code reviews.
    </p>

    <h3>Coding</h3>
    <p>I'm a full stack developer my focus is on Ruby on Rails applications. On the front end I’m working with CoffeeScript, jQuery, Haml, Sass, and Twitter Bootstrap. I prefer using a grid. I drive out user stories using Behavior Driven Development and Test Driven Development and tools like Rspec, Cucumber, and Capybara to write features that describe application behavior, which helps documentation and removes tedious QA.</p>

    <h3>Design</h3>
    <p>Websites are about information. My goal as designer is to navigate the user around that information with the right precedence by thinking about what a user will do on every page with clarity and consistency. Consistency means bringing a graphical continuity to every page through fonts, color palettes, headers and layout. I do this using Photoshop, CSS, HTML, and Javascript.</p>
  </div>
</div>
</div>

app/views/welcome/contact.html.erb
<div class="content devroye", id="home_page_contents">
  <div class="container">
    <div class="page-header">
      <h1><i class="icon-envelope-alt"></i> Contact us</h1>
    </div>
    <div class="row-fluid">
      <center>
      <h3>
        I’d love to hear from you. Interested in working together? Fill out the form below with some info about your project and I will get back to you as soon as I can. Please allow a couple days for me to respond.
      </h3>
      </center>
      <br>
      <!-- Start: CONTACT US FORM -->
      <div class="span4 offset1">
        <div class="page-header">
          <h3><i>Quick message</i></h3>
        </div>

        <%= form_for(@user_request) do |f| %> 
        
          <div class="control-group">
            <div class="controls">
<!--               <input type="text" placeholder="Name" id="inputName"> -->
              <%= f.text_field :name, :placeholder => 'Name', :id => 'inputName' %>
            </div>
          </div>
          <div class="control-group">
            <div class="controls">
              <!-- <input type="text" placeholder="Email" id="inputEmail"> -->
              <%= f.text_field :email, :placeholder => 'Email', :id => 'inputEmail' %>
            </div>
          </div>
          <div class="control-group">
            <div class="controls">
              <%= f.text_field :message, :placeholder => 'Message', :id => 'inputMessage' %>
            </div>
          </div>
          <div class="control-group">
            <div class="controls">
              <%= f.submit 'Submit', :class => 'btn btn-primary btn-large' %>
            </div>
          </div>
        <% end %>
      </div>
      <!-- End: CONTACT US FORM -->
      <!-- Start: OFFICES -->
      <div class="span5 offset1">
        <div class="page-header">
          <h3><i>Get in touch with me</i></h3>
        </div>
        <!-- <h3></h3> -->
        <div>
          <address class="pull-left">
            <p><strong>phone :</strong><br>
            +91 - 9785394039</p>
            <p><strong>email :</strong><br>
            manijain333@gmail.com</p>
            <p><strong>Address :</strong><br>
            C58A, Bhartendu Chowk,<br>
            Ambabari, jaipur (Rajasthan)<br>
            302010<br>
          </address><br><br>
        </div>
      <!-- End: OFFICES -->
      </div>
    </div>
  </div>
</div>

app/views/welcome/index.html.erb
<div class="content devroye", id="home_page_contents">
  <!-- Start: slider -->
  <div class="item">
  <div class="hero-unit">
    <div class="row-fluid">
      <div class="span4">
        <img class="thumbnail" src="assets/manish-profile.jpg">
        <div class="">
          <center><h4>Manish Jain <br> 
            Ruby On Rails developer</h4>
            <hr>
            <p>
              <i class="icon-signal"></i> (+91) 97853-94039<br>
              <i class="icon-skype"></i> skype id : manijain333<br>
              <i class="icon-envelope"></i> <a href="mailto:manijain333@gmail.com">manijain333@gmail.com </a><br>
            </p>
          </center>
        </div>
      </div>
      <div class="span8 marketting-info">
        <h2><i class="icon-briefcase"></i> Hello World! <br> Let Me Introduce MySelf</h2>
        <p>
          Hi Friends,

          I'm Manish Jain and I’m a Ruby on Rails software developer in Jaipur, Rajasthan(India), and I’ve built websites. I work on Ruby on Rails since 2011.<br><br>

          Most of my work is done in Ruby, Rails, Html and Others. I'm a passionate for Ruby on Rails It's unbeatable when it comes to rapid web application development. Much of the code in Ruby reads like regular English so it's intuitive and brings a certain ease of use - pretty ironic since Ruby originated in Japan. Ruby on Rails has a great flow, delivers fast, clean results, and lets me write beautiful code easily. It works exceptionally well with an Agile approach to software development.<br><br>

          I take a prgamatic approach to software development focus on what needs to be done how, and write good, well tested code that can adapt to changing demands in the future. I love the process of taking a client's ideas and turning them into something that doesn't just work, but works well. 
        </p>
      </div>
    </div>              
  </div>
  </div>

<!--   <div class="slider">
    <div class="container-fluid">
      <div class="carousel slide" id="heroSlider">
        <div class="carousel-inner">
          <div class="item">
            <div class="hero-unit">
              <div class="row-fluid">
                <div class="span3">
                  <img class="thumbnail" src="assets/placeholder.jpg">
                </div>
                <div class="span9 marketting-info">
                  <h2>Add more achievement</h2>
                  <p> will soon add more inforamtion about my achivement. will soon add more inforamtion about my achivement. will soon add more inforamtion about my achivement.
                  </p>
                  <h3>
                    <a class="btn pull-right" href="about.html">Learn more</a>
                  </h3>                
                </div>
              </div>          
            </div>
          </div>
          <div class="item active left">
            <div class="hero-unit">
              <div class="row-fluid">
                <div class="span3">
                  <img class="thumbnail" src="assets/placeholder.jpg">
                </div>
                <div class="span9 marketting-info">
                  <h2>Add more achievement</h2>
                  <p>
                    will soon add more inforamtion about my achivement. will soon add more inforamtion about my achivement. will soon add more inforamtion about my achivement. 
                  </p>
                  <h3>
                    <a class="btn pull-right" href="service.html">Learn more</a>
                  </h3>                      
                </div>
              </div>                  
            </div>
          </div>
          <div class="item next left">
            <div class="hero-unit">
              <div class="row-fluid">
                <div class="span3">
                  <img class="thumbnail" src="assets/manish-profile.jpg">
                  <div class="">
                    <h4>Manish Jain <br> 
                      Ruby On Rails developer</h4><br>
                  </div>
                </div>
                <div class="span9 marketting-info">
                  <h2><i class="icon-briefcase"></i> Hello World! <br> Let Me Introduce MySelf</h2>
                  <p>
                    Hi Friends,

                    I'm Manish Jain and I’m a Ruby on Rails software developer in Jaipur, Rajasthan(India), and I’ve built websites. I work on Ruby on Rails since 2011.

                    Most of my work is done in Ruby, Rails, Html and Others. I'm a passionate for Ruby on Rails It's unbeatable when it comes to rapid web application development. Much of the code in Ruby reads like regular English so it's intuitive and brings a certain ease of use - pretty ironic since Ruby originated in Japan. Ruby on Rails has a great flow, delivers fast, clean results, and lets me write beautiful code easily. It works exceptionally well with an Agile approach to software development.
                  </p>
                  <h3>
                    <a class="btn pull-right" href="product.html">Learn more</a>
                  </h3>
                </div>

              </div>                  
            </div>
          </div>
          <div class="item">
            <div class="hero-unit">
              <div class="row-fluid">
                <div class="span7 marketting-info">
                  <h2>Add more achievement</h2>
                  <p>
                    will soon add more inforamtion about my achivement. will soon add more inforamtion about my achivement. will soon add more inforamtion about my achivement.
                  </p>
                  <h3>
                    <a class="btn pull-right" href="product.html">Learn more</a>
                  </h3>                      
                </div>
                <div class="span5">
                  <img class="thumbnail" src="assets/placeholder.jpg">
                </div>
              </div>                  
            </div>
          </div>
        </div>
        <a data-slide="prev" href="#heroSlider" class="left carousel-control">‹</a>
        <a data-slide="next" href="#heroSlider" class="right carousel-control">›</a>
      </div>
    </div>
  </div> -->
  <!-- End: slider -->
  <!-- Start: PRODUCT LIST -->
<!--     <div class="container">
      <div class="page-header">
        <h2>My Projects</h2>
      </div>
      <div class="row-fluid">
        <ul class="thumbnails">
          <li class="span4">
            <div class="thumbnail">
             <img alt="product name" src="assets/placeholder-360x200.jpg">
              <div class="caption">
                <h3>Project name</h3>
                <p>
                  All details about my project. All details about my project.
                  All details about my project. All details about my project.
                  All details about my project. All details about my project.
                </p>
              </div>
              <div class="widget-footer">
                <p>
                  <a class="btn btn-primary pull-right" href="#">Read more</a>&nbsp
                </p>
              </div>
            </div>
          </li>
          <li class="span4">
            <div class="thumbnail">
             <img alt="product name" src="assets/placeholder-360x200.jpg">
              <div class="caption">
                <h3>Project name</h3>
                <p>
                  All details about my project. All details about my project.
                  All details about my project. All details about my project.
                  All details about my project. All details about my project.
                </p>
              </div>
              <div class="widget-footer">
                <p>
                  <a class="btn btn-primary pull-right" href="#">Read more</a>&nbsp
                </p>
              </div>
            </div>
          </li>
          <li class="span4">
            <div class="thumbnail">
              <img alt="product name" src="assets/placeholder-360x200.jpg">
              <div class="caption">
                <h3>Project name</h3>
                <p>
                  All details about my project. All details about my project.
                  All details about my project. All details about my project.
                  All details about my project. All details about my project.
                </p>
              </div>
              <div class="widget-footer">
                <p>
                  <a class="btn btn-primary pull-right" href="#">Read more</a>&nbsp
                </p>
              </div>
            </div>
          </li>
        </ul>
      </div>
    </div> -->
  <!-- End: PRODUCT LIST -->
</div>

app/views/welcome/portfolio.html.erb
<div class="content devroye", id="home_page_contents">
  <!-- Start: slider -->
  <div class="item">
    <div class="hero-unit">
      <div class="page-header">
        <h2><i class="icon-briefcase"></i> Portfolio</h2>
      </div>
      <h3> In-progress </h3>
    </div>
  </div>
</div>